server:
  port: 3000
spring:
  application:
    name: hiden-crowd-redis
  redis:
    host: 192.168.234.129
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
