server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
zuul:
  routes:
    crowd-portal:
      service-id: hiden-crowd-auth
      path: /**
  ignored-services: "*"
  sensitive-headers: "*"
spring:
  application:
    name: hiden-crowd-zuul
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
